### ISSUE TITLE
Failed to build apk (Configuration with name 'default' not found)

### ISSUE THREAD

**Issue by muthumani-prabhu** [cardash/react-native-openalpr#19]
I tried setting up the example given with the project. When I try running "react-native run-android" to build apk, I am seeing the following error

Evaluating project ':opencv' using build file 'C:\mani\AwesomeProject\node_modules\react-native-openaplr\android\libraries\opencv\build.gradle'.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-openalpr'.
      > Could not resolve all dependencies for configuration ':react-native-openalpr:_debugPublish'.
         > Configuration with name 'default' not found.

Looks the project stopped compilation once opencv building is reached. Would anyone please help on how to fix this issue.

Environment: 
Windows 10
Node v6.9.1
Npm v4.6.1

Other library versions are taken as it from example folder.

**Comment by scipioni** [comment]
Search for string "**openaplr**" into Example/android/settings.gradle. Replace with **openalpr**

**Comment by Progoogler** [comment]
Thanks @scipioni
