### ISSUE TITLE
Wrong confidence range

### ISSUE THREAD

**Issue by RassaLibre** [cardash/react-native-openalpr#25]
Hello,
there is this line in the docs:

    if (confidence > 0.9) {

but when I log `confidence` I get a number between 1-100. The correct check should therefore be:

    if (confidence > 90) {

**Comment by Progoogler** [comment]
Thanks for noticing this!

**Comment by RassaLibre** [comment]
The same in the example btw. :-)

**Comment by Progoogler** [comment]
Keen eye.Thanks again! =)
