### ISSUE TITLE
Add new countries with different variant types of license plates

### ISSUE THREAD

**Issue by 0x01Brain** [cardash/react-native-openalpr#31]
How to add new license plates for different cities or states for a specific country?

**Comment by dodds-cc** [comment]
I've found some config here for other countries, which you can load into the openalpr.conf file in the runtime_data folder
https://github.com/openalpr/openalpr/tree/master/runtime_data/config

**Comment by 0x01Brain** [comment]
Yes I did noticed that too, but is there some documentation that explains each line on the config or some kind of example that someone can use to add custom config for a country that does not exist in the "runtime_data" folder.

**Comment by raedhellal** [comment]
you can add a new country , in this link http://doc.openalpr.com/opensource.html#adding-a-new-country you will find how to do it and then you can add the config files after the training to the application.
