### ISSUE TITLE
PropTypes is a separate module now

### ISSUE THREAD

**Issue by gsavchenko** [cardash/react-native-openalpr#38]
I'm not sure for which version of react-native this has been implemented, however, I noticed in index.js PropTypes is imported from 'react' when in newer versions it's become its own module and should be imported from 'prop-types'.

https://www.npmjs.com/package/prop-types

I hope this helps,
George.

**Comment by RobertSasak** [comment]
My commit was never merged. https://github.com/cardash/react-native-openalpr/pull/24
