### ISSUE TITLE
Pass options to OpenALPR

### ISSUE THREAD

**Issue by felipecocco** [cardash/react-native-openalpr#5]
Is there any way currently to pass options to the OpenALPR recognizer -- plate formate, country code, etc.?

**Comment by felipecocco** [comment]
Thank you so much, @emrosenf -- excited to try it out tonight!

**Comment by emrosenf** [comment]
You're welcome, let me know how it works

**Comment by felipecocco** [comment]
I had a couple mins -- worked flawlessly, even just on screen grabs of plates!

https://streamable.com/kdjcw

**Comment by emrosenf** [comment]
Nice! Thanks for the update and the video
