### ISSUE TITLE
undefined symbols ALAssetsLibrary after update to Xcode8.3 from 8.2.1

### ISSUE THREAD

**Issue by heaversm** [cardash/react-native-openalpr#7]
Hi - had a project that would build last night - then I upgraded to XCode 8.3, now I get this error:

<img width="549" alt="screen shot 2017-04-05 at 10 27 02 am" src="https://cloud.githubusercontent.com/assets/520541/24718394/b6ffc60e-19ea-11e7-9568-5ceb740cc460.png">

Any idea how to resolve this?

**Comment by heaversm** [comment]
Resolved by adding AssetsLibrary in Link with Binaries

**Comment by esbasti** [comment]
This link help me fix this error
What it does is include 3 more libraries.

https://stackoverflow.com/questions/23634940/opencv2-framework-not-compile-with-linker-flag-objc
